johman10/flood-for-transmission

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, package.json
This simplifies the installation by not requiring the user to build the code.
Every push to master from now on will update create a date specific release as well as update the latest release.
This means that latest will always be the master version, but if something breaks the user can go and get an old version to keep their stuff up and running.
=> Auto release

src/components/Filters/Filters.svelte, src/components/Icon/Active.svelte, src/components/Icon/Icon.svelte, src/helpers/filterHelper.js
This adds an active filter which can be used to find all torrents that are currently active!
This should resolve #130.
=> Add an active filter

package-lock.json, src/components/Modal/TorrentDetail/Header/Header.svelte, src/components/TorrentList/Renderers/ProgressRenderer.svelte, src/components/TorrentList/Torrent.svelte, src/helpers/Transmission.js, src/helpers/classHelper.js, src/helpers/constants/statuses.js, src/helpers/filterHelper.js, src/helpers/stores/torrents.js
This resolves https://github.com/johman10/flood-for-transmission/issues/130.
I had misunderstood the original feature request but this should resolve it. The active filter should from now on show the torrents that have and up or download rate, or have a checking status.
=> Active filter shows torrents that are actually uploading/downloading

src/helpers/stores/torrents.js
This should resolve https://github.com/johman10/flood-for-transmission/issues/222.
=> Sorting DESC by ETA should keep infinite last

public/style/colors.css, src/components/App/App.svelte, src/components/Checkbox/Checkbox.svelte, src/components/Modal/Settings/UserInterface.svelte, src/components/Select/Select.svelte, src/helpers/stores/darkMode.js, src/helpers/stores/index.js, src/helpers/stores/switchSpeedColors.js
This allows the user to switch the upload and download color. 
Resolves: https://github.com/johman10/flood-for-transmission/issues/264.
=> Allow the user to switch the upload and download color

package-lock.json, package.json, src/components/ContextMenu/Torrent/Torrent.svelte, src/components/Modal/TorrentDetail/Files/Files.svelte, src/components/TorrentList/TorrentList.svelte, src/helpers/Transmission.js, src/helpers/stores/torrents.js
Also includes dependency updates and some css removal that was redundant.
=> Add force start option in the context menu

src/components/TorrentList/Torrent.svelte, src/helpers/actions/contextmenu.js, src/helpers/actions/index.js
This handles the ios context menu differently.
Resolves: https://github.com/johman10/flood-for-transmission/issues/241
=> Fix context menu ios

README.md
Resolves: https://github.com/johman10/flood-for-transmission/issues/330
=> Update Mac instructions in README

.github/FUNDING.yml, package-lock.json, package.json, src/components/Filters/Filters.svelte, src/helpers/filterHelper.js, src/helpers/stores/filters.js, src/helpers/stores/torrents.js
Add a priority filter for high normal and low in the same way as done for labels, trackers etc.
Resolves: https://github.com/johman10/flood-for-transmission/issues/446
=> Add priority filter

src/components/Modal/Settings/Network.svelte, src/components/TorrentList/Torrent.svelte
=> Small bugfixes

public/style/colors.css, src/components/InputFile/InputFile.svelte, src/components/Modal/Add/Add.svelte, src/components/TorrentList/TorrentDropzone.svelte, src/components/TorrentList/TorrentList.svelte, src/helpers/Transmission.js, src/helpers/fileHelper.js
This allows to drop files anywhere on the torrent list to add them to the queue.
Resolves: #414
=> Add dropzone to list

src/components/Modal/TorrentDetail/Peers/Peers.svelte, src/helpers/stores/ipAddress.js
Minor change i find quite convenient in flood especially for exotic flags:
=> Add country name as title to peer flags

src/components/Modal/Add/Add.svelte
=> Fix absolute path validation to support Windows

src/components/Modal/TorrentDetail/Files/Files.svelte
Resolves: https://github.com/johman10/flood-for-transmission/issues/529
=> Sort files in Torrent Files modal

rollup.config.mjs
`!!"false"` evaluates to true.
=> Fix ssl env variable

src/components/TorrentList/TorrentList.svelte
Selects all torrents on <kbd>Ctrl/Cmd</kbd> + <kbd>A</kbd>.
=> Select all shortcut

src/components/Modal/Add/Add.svelte, src/components/Modal/Location/Location.svelte, src/components/Modal/Settings/UserInterface.svelte, src/helpers/constants/paths.js
Fixes: https://github.com/johman10/flood-for-transmission/issues/551
=> Fix path pattern regex

src/components/TorrentList/TorrentList.svelte
=> Fix select all in inputs

src/helpers/Transmission.js, src/helpers/stores/session.js, src/helpers/stores/sessionStats.js, src/helpers/stores/torrentDetails.js, src/helpers/stores/torrents.js
In an attempt to handle https://github.com/johman10/flood-for-transmission/issues/538 I ended up rewriting some logic in the Transmission class. However, this doesn't really resolve any issues, it's more of a refactoring at this point.
=> Improve API requests

src/components/Graph/SpeedLimit.svelte
Resolves: https://github.com/johman10/flood-for-transmission/issues/554
References: https://github.com/johman10/flood-for-transmission/pull/557
=> Prevent speed limit wrapping

src/components/Modal/TorrentDetail/Files/Files.svelte, src/helpers/stores/torrentDetails.js
Resolves: https://github.com/johman10/flood-for-transmission/issues/555
References: https://github.com/johman10/flood-for-transmission/pull/556
=> Fix changing priority on a file

.github/workflows/release.yml, src/components/Modal/Add/Add.svelte, src/components/TopBar/TopBar.svelte
@sriranganathan I'm taking the liberty to open your changes as a PR. I noticed you had applied these changes and now there is an issue requesting to the same feature.
Resolves: https://github.com/johman10/flood-for-transmission/issues/593
=> Add support for opening the Add modal via magnet link in URL
